# http server conf
HttpSvrPort=14000
# worker server conf
WorkerSvrPort=14001
# ssl conf
server.ssl.key-store=/tmp/CommMngr.p12
server.ssl.key-store-password=CommMngr
# redis conf
redis.url=127.0.0.1:6379
redis.password=Comm
# mongo conf
mongodb.url=mongodb://Comm:Comm@127.0.0.1:27017/Comm

